language: java
jdk:
- oraclejdk8
env:
  global:
  - TERM=dumb
  - secure: ehLpQINxcXcrxwaoe73XgVxuTbikrznJev+vWerQybqEHipJe4Ad1wTihwaXU0rD5P3K0+heU0Yz68Xy4q3DLJ0gEji/Aao+AREzQOEjHw9t5YaI51TQOVxI0bIPuABZCQDl1tPW5ZrWS4tlY8odE4R4pC058z7cviM9rHPr+ZE=
  - secure: FwexcJrdQGM7am1IKMCzGIiS8zO0PjYG6FMMuPOX3KvLhMzVFwnyIxui5EEf8P3VBXc9K4JfbHMJ3MAZhGq0U08Se3PvHDHfTJJ8i6KUOBnbsDu/Le2ZE/ksBeGATBM0HWAThz80tTll+zvaubTeIhR8nrF/9HzbspT93TTb+6o=
install:
- ./gradlew clean test build publish publishBintray
