language: java
env:
  global:
    - TERM=dumb
    - secure: "OxL82zm3cyxXSkvdvbTBEm8k/zSARc3l4vgrIbuRj4KXG3sXBOX1GCWDF+ROOs75eI7mmBpkt5fXrznjJOXsKJmuWVJSLkDji+qVVvXV1Y3n4fJ/x3HJAVML3ATfWA/5IeVt0r4PNpKeiLQ9R+kaBKM1sXW2P98IqSxURs4qGWg="
    - secure: "HBiMlRgmc8TEeZRED1pRulg8kcJU/dOdlly5T7mpg2trLcOkgoAqVuwlNOAUYIs9BWy3rki06bG1r/mEE4J11KYY7DTGeHB+2p92T6jdtoiwdaUrwra2+QSQdMOe2+PmVR9U6a8UfaXO33KZA1A8fVKxO6DMjUCukrHVoOlTu1A="
install: 
  - "./gradlew clean test build publish publishBintray"