language: java
env:
  global:
    - TERM=dumb
    - secure: "GHQxdKoV64z9XRA20sRLc0P9RvjwOJo/v9rsvmXrH/0g/3yrkJuMW6QRmXgibW5s7EUPWC89HZt/t6gsRHSP6FKombLAWcqcreDNWm/qMQ88CZyWfeH+UrwNKCE4MLrqSt3dg/BE9BpIHasR2iw9Pfv3FpfuLiOyGNgud2j2MKw="
    - secure: "kLUeIZIkE1XHv/kNh5oFPMsGiMd3FC5KAtM8Z4ZJ6e3dQ6sAAKY72yRIhT/AY8xY6ZS2iBqMH+A9VLP9IxayGNQiVMd1gctxcwBVbUzE+3jphkkpIzhNLl5ScLziLyz4nVpRTCJglxtGkem3hXFsCj2zk+KUTMI3cQj4fHRY1js="
install: 
  - "./gradlew clean test build publish publishBintray"